// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoOFDBD4DDMk3t5UTYEB5rdoS4ha0VzC4',
    appId: '1:637392038871:web:71d6d8020457ab35b4b992',
    messagingSenderId: '637392038871',
    projectId: 'ecofarmai',
    authDomain: 'ecofarmai.firebaseapp.com',
    storageBucket: 'ecofarmai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2PLGjoAHX_uBCRkseX8dFtBGX-glo2o',
    appId: '1:637392038871:android:57e13b1e3ede672fb4b992',
    messagingSenderId: '637392038871',
    projectId: 'ecofarmai',
    storageBucket: 'ecofarmai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQskYfclJgUUUKIFNIKyB_d21_tgepQJA',
    appId: '1:637392038871:ios:fc6a99aa39f275e7b4b992',
    messagingSenderId: '637392038871',
    projectId: 'ecofarmai',
    storageBucket: 'ecofarmai.firebasestorage.app',
    iosBundleId: 'com.example.ecoFarmAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQskYfclJgUUUKIFNIKyB_d21_tgepQJA',
    appId: '1:637392038871:ios:fc6a99aa39f275e7b4b992',
    messagingSenderId: '637392038871',
    projectId: 'ecofarmai',
    storageBucket: 'ecofarmai.firebasestorage.app',
    iosBundleId: 'com.example.ecoFarmAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoOFDBD4DDMk3t5UTYEB5rdoS4ha0VzC4',
    appId: '1:637392038871:web:aa2bf2b9f87b654bb4b992',
    messagingSenderId: '637392038871',
    projectId: 'ecofarmai',
    authDomain: 'ecofarmai.firebaseapp.com',
    storageBucket: 'ecofarmai.firebasestorage.app',
  );
}
